apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
metadata:
  name: etcd
  labels:
    component: etcd
spec:
  ports:
    - port: {{ etcd_peer_port }}
      name: etcd-server
    - port: {{ etcd_client_port }}
      name: etcd-client
  clusterIP: None
  selector:
    component: "etcd"